apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trivy
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'trivy-{{cluster}}'
    spec:
      project: devops
      source:
        repoURL: https://github.com/brunogianini/argocd-canal-deploy-config.git
        targetRevision: HEAD
        path: ./kubernetes
      destination:
        server: '{{url}}'
        namespace: teste
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 2
          backoff:
            duration: "5s"
            factor: 2
            maxDuration: "3m0s"
