apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: teste-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.cluster}}-teste'
    spec:
      project: default
      source:
        repoURL: https://github.com/brunogianini/canal-deploy-teste.git
        targetRevision: HEAD
        path: ./kubernetes
      destination:
        server: '{{.url}}'
        namespace: ""
