apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/brunogianini/argocd-canal-deploy-config.git
    targetRevision: HEAD
    path: ./kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
